<!--Свидания+Бизнес+Интересы-->
<div class="content-block main-list hidden-mobile">
	<div class="dates">
		<div class="header">
			<h3>Cвидание </h3>
			<button class="btn btn-ico btn-ico-rotate-g"></button>
		</div>
		<div class="data">
			<a href="#" class="photo">
				<img class="photo" src="http://www.placehold.it/200x200/eee/aaa&amp;text=no-image">
				<span class="username">Роман</span>
			</a>
		</div>
	</div>
	<div class="business">
		<div class="header">
			<h3>Бизнес </h3>
			<button class="btn btn-ico btn-ico-rotate-g"></button>
		</div>
		<div class="data">
			<a href="#" class="photo">
				<img class="photo" src="http://www.placehold.it/200x200/eee/aaa&amp;text=no-image">
				<span class="username">Роман</span>
			</a>
		</div>
	</div>
	<div class="goals">
		<div class="header">
			<h3>Цели и интересы</h3>
			<button class="btn btn-ico btn-ico-rotate-g"></button>
		</div>
		<div class="data">
			<a href="#" class="photo">
				<img class="photo" src="http://www.placehold.it/150x150/eee/aaa&amp;text=no-image">
				<span class="username">Роман</span>
			</a>
		</div>
	</div>
</div>