<?php

$item = $this->item;

?>

<div class="row-fluid">
	<div class="span12">
		<p class="text-center"><small><?= $item['tpl_key']?> (ID: <?= $item['id']?>)</small></p>
		<h5>
			<?= $item['name']?>
		</h5>
	</div>
</div>

<div class="row-fluid">
	<div class="span6">
		<input id="Sex_<?= $item['id']?>" type="hidden" name="sex" value="neutral">
		<img src="/img/flags/ru.png"> Текст SMS
		<textarea id="TextRu_<?= $item['id']?>" rows="7" class="input-block-level" name="text_ru"><?= $item['text_ru']?></textarea>
	</div>
	<div class="span6">
		<img src="/img/flags/en.png"> Текст SMS
		<textarea id="TextEn_<?= $item['id']?>" rows="7" class="input-block-level" name="text_en"><?= $item['text_en']?></textarea>
	</div>
</div>
<p class="text-center">
	<button class="btn btn-success" onclick="saveTpl(<?= $item['id']?>, 'sms')"><i class="icon-ok icon-white"></i> Сохранить</button>
</p>