# ************************************************************
# Sequel Pro SQL dump
# Версия 4096
#
# http://www.sequelpro.com/
# http://code.google.com/p/sequel-pro/
#
# Адрес: 127.0.0.1 (MySQL 5.6.14)
# Схема: db_onthelist
# Время создания: 2013-11-21 17:44:09 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Дамп таблицы templates_email
# ------------------------------------------------------------

DROP TABLE IF EXISTS `templates_email`;

CREATE TABLE `templates_email` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `tpl_key` varchar(30) NOT NULL DEFAULT '',
  `sex` enum('neutral','male','female') NOT NULL DEFAULT 'neutral',
  `subject_ru` varchar(255) DEFAULT NULL,
  `text_ru` text,
  `subject_en` varchar(255) DEFAULT NULL,
  `text_en` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `templates_email` WRITE;
/*!40000 ALTER TABLE `templates_email` DISABLE KEYS */;

INSERT INTO `templates_email` (`id`, `name`, `tpl_key`, `sex`, `subject_ru`, `text_ru`, `subject_en`, `text_en`)
VALUES
	(1,'Письмо пользователю отправляемое ему при новой регистрации','registration_new_user','neutral','OnTheList.ru - Получена заявка на регистрацию','<p>%first_name%, здравствуйте!</p>\r\r<p>Спасибо за Ваш интерес к Клубу OnTheList. Ваша заявка будет рассмотрена в ближайшее время, мы сообщим Вам о результатах ее рассмотрения по электронной почте.</p>\r\r<p>С уважением,<br>\rЮлия<br>\rМенеджер Клуба OnTheList<br>\rmailto: ys@onthelist.ru<br>\rsite: <a href=\"http://onthelist.ru\">www.onthelist.ru</a></p>\r\r<p>=======<br>\rВнимание!<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - Your application has been received','<p>Dear %first_name%,</p>\r\r<p>Thank you for your interest in OnTheList Private Club. Your application will be reviewed shortly, we will inform you by email.</p>\r\r<p>Kind regards,<br>\rYulia<br>\rManager, OnTheList Private Club<br>\rmailto: ys@onthelist.ru<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(2,'Запрос встретиться (от женщины мужчине)','invite_request','male','OnTheList.ru - Вас приглашают встретиться!','<p>Уважаемый %first_name%, здравствуйте!</p>\r\r<p>%my_name% приглашает Вас встретиться.<br>\rДля того чтобы принять или отклонить приглашение, зайдите на страницу Встречи на сайте www.onthelist.ru.</p>\r\r<p>С уважением,<br>\rКлуб OnTheList<br>\rSite: <a href=\"http://onthelist.ru\">www.onthelist.ru</a></p>\r\r<p>=======<br>\rВнимание!<br>\rЭто письмо сгенерировано автоматически и не требует ответа.<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - You have received a meeting request!','<p>Dear %first_name%,</p>\r\r<p>%my_name% sent you a meeting request. Please, accept or decline the invitation on www.onthelist.ru.</p>\r\r\n<p>Kind regards,<br>\rOnTheList Private Club<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(3,'Запрос встретиться (от мужчины женщине)','invite_request','female','OnTheList.ru - Вас приглашают встретиться!','<p>Уважаемая %first_name%, здравствуйте!</p>\r\r<p>%my_name% приглашает Вас встретиться.<br>\rДля того чтобы принять или отклонить приглашение, зайдите на страницу Встречи на сайте www.onthelist.ru.</p>\r\r<p>С уважением,<br>\rКлуб OnTheList<br>\rSite: <a href=\"http://onthelist.ru\">www.onthelist.ru</a></p>\r\r<p>=======<br>\rВнимание!<br>\rЭто письмо сгенерировано автоматически и не требует ответа.<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - You have received a meeting request!','<p>Dear %first_name%,</p>\r\r<p>%my_name% sent you a meeting request. Please, accept or decline the invitation on www.onthelist.ru.</p>\r\r<p>Kind regards,<br>\rOnTheList Private Club<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(4,'Отказ от свидания','invite_reject','female','OnTheList.ru - Ваше приглашение встретиться не принято','<p>Здравствуйте %first_name%,</p>\r\r<p>К сожалению, %my_name% отклонил Ваше приглашение встретиться.<br></p>\r\r<p>С уважением,<br>\rКлуб OnTheList<br>\rSite: <a href=\"http://onthelist.ru\">www.onthelist.ru</a></p>\r\r<p>=======<br>\rВнимание!<br>\rЭто письмо сгенерировано автоматически и не требует ответа.<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - Your meeting request was declined','<p>Dear %first_name%,</p>\r\r<p>Unfortunatly, %my_name% declined your meeting request.</p>\r\r<p>Kind regards,<br>\rOnTheList Private Club<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(5,'Отказ от свидания','invite_reject','male','OnTheList.ru - Ваше приглашение встретиться не принято','<p>Здравствуйте %first_name%,</p>\r\r<p>К сожалению, %my_name%, отклонила Ваше приглашение встретиться.<br></p>\r\r<p>С уважением,<br>\rКлуб OnTheList<br>\rSite: <a href=\"http://onthelist.ru\">www.onthelist.ru</a></p>\r\r<p>=======<br>\rВнимание!<br>\rЭто письмо сгенерировано автоматически и не требует ответа.<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - Your meeting request was declined','<p>Dear %first_name%,</p>\r\r<p>Unfortunatly, %my_name% declined your meeting request. </p>\r\r<p>Kind regards,<br>\rOnTheList Private Club<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(7,'Смена пароля','new_password','neutral','OnTheList.ru - Ваш ноВый пароль','<p>Здравствуйте %first_name%,</p>\r\r<p>Ваш пароль для доступа в личный кабинет на сайте Клуба OnTheList (www.onthelist.ru) изменен.<br>\rНовый пароль: %new_password%</p>\r\r<p>Если Вы не ничего не меняли, сообщите нам об этом.</p>\r\r\n<p>С уважением,<br>\rКлуб OnTheList<br>\rSite: <a href=\"http://onthelist.ru\">www.onthelist.ru</a></p>\r\r<p>=======<br>\rВнимание!<br>\rЭто письмо сгенерировано автоматически и не требует ответа.<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - Your new password','<p>Dear %first_name%,</p>\r\r<p>Your password for OnTheList Private Club (www.onthelist.ru/en) has been changed.<br>\rYour new password is %new_password%.</p>\r\r<p>Kind regards,<br>\rOnTheList Private Club<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(8,'Принято приглашение встретиться','invite_yes','male','OnTheList.ru - Ваше приглашение встретиться принято','<p>Уважаемый %first_name%, здравствуйте!</p>\r\r<p>%my_name% приняла Ваше приглашение.</p>\r\r<p>Встреча назначена на %day%.%month%.%year%, в %time%.</p>\r\r<p>Контактные данные девушки и Выбранное ей место Вы можете увидеть в разделе Встречи на сайте Клуба <a href=\"http://onthelist.ru\">OnTheList</a></p>\r\r<p>С уважением,<br>\rКлуб OnTheList<br>\rSite: <a href=\"http://onthelist.ru\">www.onthelist.ru</a></p>\r\r<p>=======<br>\rВнимание!<br>\rЭто письмо сгенерировано автоматически и не требует ответа.<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - Your invitation was accepted','<p>Dear %first_name%,<p>\r\r<p>%my_name% has accepted your invitation.<br>\rThe meeting has been scheduled on %day% %month% %year%, at %time%.</p>\r\r<p>Her contact details and the place she chose you can find on www.onthelist.ru/en</p>\r\r<p>Kind regards,<br>\rOnTheList Private Club<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(9,'Принято приглашение встретиться','invite_yes','female','OnTheList.ru - Ваше приглашение встретиться принято','<p>Уважаемая %first_name%, здравствуйте!</p>\r\r<p>%my_name% принял Ваше приглашение.</p>\r\r<p>Встреча назначена на %day%.%month%.%year%, в %time%.</p>\r\r<p>Контактные данные мужчины и Выбранное им место встречи Вы можете увидеть в разделе Встречи на сайте Клуба OnTheList (www.onthelist.ru)</p>\r\r<p>С уважением,<br>\rКлуб OnTheList<br>\rSite: <a href=\"http://onthelist.ru\">www.onthelist.ru</a></p>\r\r<p>=======<br>\rВнимание!<br>\rЭто письмо сгенерировано автоматически и не требует ответа.<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - Your invitation was accepted','<p>Dear %first_name%,</p>\r\r<p>%my_name% has accepted your invitation.<br>\rThe meeting has been scheduled on %day% %month% %year%, at %time%.</p>\r\r<p>His contact details and the place he selected for the meeting you can find on www.onthelist.ru/en</p>\r\r<p>Kind regards,<br>\rOnTheList Private Club<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(10,'Задан вопрос (платный или бесплатный)','questions_send_free','male','OnTheList.ru - Вам задали вопросы','<p>Здравствуйте %first_name%,</p>\r\r<p>%my_name% интересуется Вами и задает Вам несколько вопросов. Вы можете ответить на них в разделе Общение на сайте www.onthelist.ru.</p>\r\r<p>С уважением,<br>\rКлуб OnTheList<br>\rSite: <a href=\"http://onthelist.ru\">www.onthelist.ru</a></p>\r\r<p>=======<br>\rВнимание!<br>\rЭто письмо сгенерировано автоматически и не требует ответа.<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - You received some questions','<p>Dear %first_name%,</p>\r\r<p>%my_name% is interested in you and asked you a few questions. You can reply on www.onthelist.ru/en</p>\r\r<p>Kind regards,<br>\rOnTheList Private Club<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(11,'Задан вопрос (платный или бесплатный)','questions_send_free','female','OnTheList.ru - Вам задали вопросы','<p>Здравствуйте %first_name%,</p>\r\r<p>%my_name% интересуется Вами и задает Вам несколько вопросов. Вы можете ответить на них в разделе Общение на сайте OnTheList.ru (www.onthelist.ru)</p>\r\r<p>С уважением,<br>\rКлуб OnTheList<br>\rSite: <a href=\"http://onthelist.ru\">www.onthelist.ru</a></p>\r\r<p>=======<br>\rВнимание!<br>\rЭто письмо сгенерировано автоматически и не требует ответа.<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - You received some questions','<p>Dear %first_name%,</p>\r\r<p>%my_name% is interested in you and asked you a few questions. You can reply at www.onthelist.ru/en</p>\r\r<p>Kind regards,<br>\rOnTheList Private Club<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(12,'Добавление в фавориты','favorite_add','male','OnTheList.ru - Вас добавили в избранные контакты','<p>Уважаемый %first_name%, здравствуйте!</p>\r\r<p>Сообщаем Вам, что %my_name% интересуется Вами и добавила в свои избранные контакты.</p>\r\r<p>С уважением,<br>\rКлуб OnTheList<br>\rSite: <a href=\"http://onthelist.ru\">www.onthelist.ru</a></p>\r\r<p>=======<br>\rВнимание!<br>\rЭто письмо сгенерировано автоматически и не требует ответа.<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - You are added to Favorites','<p>Dear %first_name%,</p>\r\r<p>We inform you that %my_name% likes your profile and added you to her Favorite contacts.</p>\r\r<p>Kind regards,<br>\rOnTheList Private Club<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(13,'Добавление в фавориты','favorite_add','female','OnTheList.ru - Вас добавили в избранные контакты','<p>Уважаемая %first_name%, здравствуйте!</p>\r\r<p>Сообщаем Вам, что %my_name% интересуется Вами и добавил Вас в свои избранные контакты.</p>\r\r<p>С уважением,<br>\rКлуб OnTheList<br>\rSite: <a href=\"http://onthelist.ru\">www.onthelist.ru</a></p>\r\r<p>=======<br>\rВнимание!<br>\rЭто письмо сгенерировано автоматически и не требует ответа.<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - You are added to Favorites','<p>Dear %first_name% ,</p>\r\r<p>We inform you that %my_name% likes your profile and added you to his Favorite contacts.</p>\r\r<p>Kind regards,<br>\rOnTheList Private Club<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(14,'Предложение об обмене контактами','exchange_contact','neutral','OnTheList.ru - Вам предлагают обменяться телефонами','<p>Здравствуйте %first_name%,</p>\r\r<p>%my_name% предлагает Вам обменяться контактами, чтобы встретиться позже.<br>\rВы можете принять или отклонить данное приглашение на сайте Клуба OnTheList.ru (www.onthelist.ru)</p>\r\r<p>С уважением,<br>\rКлуб OnTheList<br>\rSite: <a href=\"http://onthelist.ru\">www.onthelist.ru</a></p>\r\r<p>=======<br>\rВнимание!<br>\rЭто письмо сгенерировано автоматически и не требует ответа.<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - New request to exchange phones','<p>Dear %first_name%, </p>\r\r<p>%my_name% offered you to exchange phone numbers so that you can meet later.<br>\rYou can accept or decline the invitation on www.onthelist.ru/en</p>\r\r<p>Kind regards,<br>\rOnTheList Private Club<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(15,'Обмен контактами состоялся','exchange_contact_yes','female','OnTheList.ru - Предложение обменяться телефонами принято','<p>Здравствуйте %first_name%,</p>\r\r<p>%my_name% принял Ваше предложение обменяться телефонами.<br>\rЕго телефон Вы можете посмотреть в разделе Встречи на сайте Клуба OnTheList.ru (www.onthelist.ru)</p>\r\r<p>С уважением,<br>\rКлуб OnTheList<br>\rSite: <a href=\"http://onthelist.ru\">www.onthelist.ru</a></p>\r\r<p>=======<br>\rВнимание!<br>\rЭто письмо сгенерировано автоматически и не требует ответа.<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - Your request to exchange phones was accepted','<p>Dear %first_name%,</p>\r\r<p>%my_name% accepted your invitation to exchange phone numbers.<br>\rYou can find his phone number on www.onthelist.ru/en</p>\r\r<p>Kind regards,<br>\rOnTheList Private Club<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(16,'Обмен контактами состоялся','exchange_contact_yes','male','OnTheList.ru - Предложение обменяться телефонами принято','<p>Здравствуйте %first_name%,</p>\r\r<p>%my_name% приняла Ваше предложение обменяться телефонами.<br>\rКонтактную информацию Вы можете посмотреть на сайте Клуба OnTheList.ru (www.onthelist.ru)</p>\r\r<p>С уважением,<br>\rКлуб OnTheList<br>\rSite: <a href=\"http://onthelist.ru\">www.onthelist.ru</a></p>\r\r<p>=======<br>\rВнимание!<br>\rЭто письмо сгенерировано автоматически и не требует ответа.<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - Your request to exchange phones was accepted','<p>Dear %first_name%,</p>\r\r<p>%my_name% accepted your invitation to exchange phone numbers. <br>\rYou can find her phone number on www.onthelist.ru/en</p>\r\r<p>Kind regards,<br>\rOnTheList Private Club<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(17,'Активация профиля','activation_profile','neutral','OnTheList.ru - Ваша заявка в Клуб одобрена','<p>%first_name%, здравствуйте!</p>\n\n<p>Поздравляем, Ваша заявка в Клуб OnTheList была одобрена!</p>\n\n<p>Пожалуйста, воспользуйтесь своим логином и паролем для входа в Клуб.</p>\n\n<p>Ваш логин: %email% <br>\nВаш пароль: Вы указали при регистрации. Если Вы забыли пароль воспользуйтесь функцией восстановления пароля.</p>\n\n<p>С уважением,<br>\nЮлия<br>\nМенеджер Клуба OnTheList<br>\nmailto: ys@onthelist.ru<br>\nsite: www.onthelist.ru</p>\n\n<p>=======<br>\nВнимание!<br>\nПочтовый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - Your application was approved','<p>Dear %first_name%,</p>\n\n<p>Congratulations, your application to OnTheList Private Club has been approved! Please, log in to the website using your login and password.</p>\n\n<p>Login: %email%<br>\nPassword: the password you set when creating the account. If you forgot your password, please, use the password recovery function.</p>\n\n<p>Kind regards,<br>\nYulia<br>\nManager, OnTheList Private Club<br>\nmailto: ys@onthelist.ru<br>\nSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\n\n<p>=======<br>\nAttention!<br>\nYou can\'t contact us by replying to this email.</p>'),
	(18,'Исключение пользователя из клуба','delete_user','neutral','OnTheList.ru - Вам отказано в членстве в Клубе','<p>%first_name%, здравствуйте!</p>\r\r<p>С сожалением сообщаем Вам, что на основании отзывов других пользователей нашего сайта, администрацией Клуба было принято решение удалить Ваш аккаут.<br>\rДанное решение окончательное и не подлежит пересмотру.</p>\r\r<p>С уважением,<br>\rЮлия<br>\rМенеджер Клуба OnTheList<br>\rmailto: ys@onthelist.ru<br>\rsite: <a href=\"http://onthelist.ru\">www.onthelist.ru</p>\r\r<p>=======<br>\rВнимание!<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - Your membership was cancelled','<p>Dear %first_name%,</p>\r\r<p>Unfortunatly, based on the feedback of other users, the administration of the Club decided to cancel your membership.<br>\rThis decision is final and can\'t be reversed.</p>\r\r<p>Kind regards,<br>\rYulia<br>\rManager, OnTheList Private Club<br>\nmailto: ys@onthelist.ru<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(19,'Отклонить заявку','delete_registration_new_user','neutral','OnTheList.ru - Ваша заявка на вступление в Клуб отклонена','<p>%first_name%, здравствуйте!</p>\r\r<p>Мы очень внимательно рассмотрели Вашу заявку, но, к сожалению, в данный момент мы не можем предложить Вам вступить в Клуб OnTheList (www.onthelist.ru).<br>\rСейчас мы получаем большой поток заявок от кандидатов, поэтому, к сожалению, не можем объяснять причины отказа в индивидуальном порядке.<br>\rВы можете попробовать подать заявку повторно через 6 месяцев.</p>\r\r<p>С уважением,<br>\rКлуб OnTheList<br>\rSite: <a href=\"http://onthelist.ru\">www.onthelist.ru</a></p>\r\r<p>=======<br>\rВнимание!<br>\rЭто письмо сгенерировано автоматически и не требует ответа.<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - Your application was declined','<p>Dear %first_name%,</p>\r\r<p>We carefully reviewed your application, but, unfortunately, we can’t offer you OnTheList Club (www.onthelist.ru) membership at the moment.<br>\rWe receive a large volume of applications every day, and for this reason, we can\'t explain our decisions on an individual basis.<br>\rYou can try to reapply in 6 months.</p>\r\r<p>Kind regards,<br>\rOnTheList Private Club<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(20,'Удачное свидание','successful_date','male','OnTheList.ru - Удачное свидание!','<p>Уважаемый %first_name%, здравствуйте!</p>\r\r<p>У Вас было свидание с %my_name%. После свидания, она оставила отзыв, в котором ответила, что хотела бы встретиться с Вами снова.</p>\r\r<p>Поздравляем и желаем удачи!</p>\r\r<p>С уважением,<br>\rЮлия<br>\rМенеджер Клуба OnTheList<br>\rmailto: ys@onthelist.ru<br>\rsite: <a href=\"http://onthelist.ru\">www.onthelist.ru</p>\r\r<p>=======<br>\rВнимание!<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - Successful date!','<p>Dear %first_name%,</p>\r\r<p>You had a date with %my_name%. After your date she left a feedback where she indicated that she would like to meet you again.</p>\r\r<p>Congratulations and good luck!</p>\r\r<p>Kind regards,<br>\rYulia<br>\rManager, OnTheList Private Club<br>\nmailto: ys@onthelist.ru<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(21,'Удачное свидание','successful_date','female','OnTheList.ru - Удачное свидание!','<p>Уважаемая %first_name%, здравствуйте!</p>\r\r<p>У Вас было свидание с %my_name%. После свидания, он оставила отзыв, в котором ответил, что хотел бы встретиться с Вами снова.</p>\r\r<p>Поздравляем и желаем удачи!</p>\r\r<p>С уважением,<br>\rЮлия<br>\rМенеджер Клуба OnTheList<br>\rmailto: ys@onthelist.ru<br>\rsite: <a href=\"http://onthelist.ru\">www.onthelist.ru</p>\r\r<p>=======<br>\rВнимание!<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - Successful date!','<p>Dear %first_name%,</p>\r\r<p>You had a date with %my_name%. After your date he left a feedback where he indicated that he would like to meet you again.</p>\r\r<p>Congratulations and good luck!</p>\r\r<p>Kind regards,<br>\rYulia<br>\rManager, OnTheList Private Club<br>\nmailto: ys@onthelist.ru<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(22,'Восстановление пароля','password_recovery','neutral','OnTheList.ru - Восстановление пароля','<p>%first_name%, здравствуйте!</p>\r\r<p>Ваш новый пароль для доступа на сайт <a href=\"http://onthelist.ru\">OntheList.ru</a>: %new_password% </p>\r\r<p>С уважением,<br>\rКлуб OnTheList<br>\rSite: <a href=\"http://onthelist.ru\">www.onthelist.ru</a></p>\r\r<p>=======<br>\rВнимание!<br>\rЭто письмо сгенерировано автоматически и не требует ответа.<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - Password recovery','<p>Dear %first_name%,</p>\r\r<p>Your new password for <a href=\"http://onthelist.ru/en\">OnTheList.ru</a>: %new_password%</p>\r\r<p>Kind regards,<br>\rOnTheList Private Club<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(23,'Отказ от обмена контактами','exchnage_contact_no','female','OnTheList.ru - Предложение обменяться телефонами отклонено','<p>Здравствуйте %first_name%,</p>\r\r<p>К сожалению, %my_name% отклонил Ваше предложение обменяться телефонами.<br></p>\r\r<p>С уважением,<br>\rКлуб OnTheList<br>\rSite: <a href=\"http://onthelist.ru\">www.onthelist.ru</a></p>\r\r<p>=======<br>\rВнимание!<br>\rЭто письмо сгенерировано автоматически и не требует ответа.<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - Your request to exchange phones was declined','<p>Dear %first_name%,</p>\r\r<p>Unfortunatly, %my_name% declined your offer to exchange phone numbers.</p>\r\r<p>Kind regards,<br>\rOnTheList Private Club<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(24,'Отказ от обмена контактами','exchnage_contact_no','male','OnTheList.ru - Предложение обменяться телефонами отклонено','<p>Здравствуйте %first_name%,</p>\r\r<p>К сожалению, %my_name% отклонила Ваше предложение обменяться телефонами.<br></p>\r\r<p>С уважением,<br>\rКлуб OnTheList<br>\rSite: <a href=\"http://onthelist.ru\">www.onthelist.ru</a></p>\r\r<p>=======<br>\rВнимание!<br>\rЭто письмо сгенерировано автоматически и не требует ответа.<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - Your request to exchange phones was declined','<p>Dear %first_name%,</p>\r\r<p>Unfortunatly, %my_name% declined your offer to exchange phone numbers.</p>\r\r<p>Kind regards,<br>\rOnTheList Private Club<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(25,'Ответ на вопрос','answer_ok','female','OnTheList.ru - Вам ответили на вопросы','<p>Здравствуйте %first_name%,</p>\r\r<p>%my_name% ответил на Ваши вопросы. Вы можете посмотреть ответы в разделе Общение на сайте OnTheList.ru (www.onthelist.ru)</p>\r\r<p>С уважением,<br>\rКлуб OnTheList<br>\rSite: <a href=\"http://onthelist.ru\">www.onthelist.ru</a></p>\r\r<p>=======<br>\rВнимание!<br>\rЭто письмо сгенерировано автоматически и не требует ответа.<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - Your received answers to your questions','<p>Dear %first_name%,</p>\r\r<p>%my_name% answered your questions. You can read answers on www.onthelist.ru/en</p>\r\r<p>Kind regards,<br>\rOnTheList Private Club<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(26,'Ответ на вопрос','answer_ok','male','OnTheList.ru - Вам ответили на вопросы','<p>Здравствуйте %first_name%,</p>\r\r<p>%my_name% ответила на Ваши вопросы. Вы можете посмотреть ответы в разделе Общение на сайте OnTheList.ru (www.onthelist.ru)</p>\r\r<p>С уважением,<br>\rКлуб OnTheList<br>\rSite: <a href=\"http://onthelist.ru\">www.onthelist.ru</a></p>\r\r<p>=======<br>\rВнимание!<br>\rЭто письмо сгенерировано автоматически и не требует ответа.<br>\rПочтоВый ящик, с которого Вы получили это письмо, не является контактным.</p>','OnTheList.ru - Your received answers to your questions','<p>Dear %first_name%,</p>\r\r<p>%my_name% answered your questions. You can read answers on www.onthelist.ru/en</p>\r\r<p>Kind regards,<br>\rOnTheList Private Club<br>\rSite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\r\r<p>=======<br>\rAttention!<br>\rYou can\'t contact us by replying to this email.</p>'),
	(27,'Новый пользователь','register','neutral','Добро пожаловать в OnTheList Private Club','<p>Здравствуйте!</p>\n\n<p>Поздравляем, Вы сделали первый шаг на пути к членству в Клубе OnTheList!</p>\n\n<p>Пожалуйста, перейдите по ссылке предложенной ниже для подтверждения регистрации.</p>\n\n<p>Ваш логин: %email% <br>\nСсылка для подтверждения: <a href=\"http://onthelist.ru/user/register/activation/key/%activation_key%\">http://onthelist.ru/user/register/activation/key/%activation_key%</a></p>\n\n<p>С уважением,<br>\nЮлия<br>\nМенеджер Клуба OnTheList<br>\nmailto: ys@onthelist.ru<br>\nsite: www.onthelist.ru</p>\n\n<p>=======<br>\nВнимание!<br>\nПочтоВый ящик, с которого Вы получили это письмо, не является\nконтактным.</p>','Welcome to OnTheList Private Club','<p>Hello!</p>\n\n<p>Congratulations, you are on the way to becoming the Club member!</p>\n\n<p>Please, follow the link below to gain a limited access to the Club and complete registration.</p>\n\n<p>Your login: %email% <br>\nYour confirmation link: <a href=\"http://onthelist.ru/en/user/register/activation/key/%activation_key%\">http://onthelist.ru/en/user/register/activation/key/%activation_key%</a></p>\n\n<p> Sincerely yours,<br>\nYulia<br>\nManager, OnTheList Private Club <br>\nmailto: ys@onthelist.ru<br>\nsite: <a href=\"http://onthelist.ru/en/\">www.onthelist.ru/en</p>\n\n<p>=======<br>\nAttention!<br>\nYou can\'t reach OnTheList Private Club by replying to this email </p>');

/*!40000 ALTER TABLE `templates_email` ENABLE KEYS */;
UNLOCK TABLES;



/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
