<?
//$this->inlineScript()->appendFile('/js/libs/jquery.form.js');
?>
<div class="container">
	<div class="auth-box">
		<script src="//ulogin.ru/js/ulogin.js"></script>
		<?
		$lang = $this->translate()->getLocale();
		$socUlr = ($lang == LANG_DEFAULT) ? $_SERVER['HTTP_HOST'].'%2Fuser%2F' : $_SERVER['HTTP_HOST'].'%2F' . $lang .'%2Fuser%2F';
		?>
		<div class="social-auth" id="uLogin" data-ulogin="display=buttons;fields=first_name,last_name,sex,bdate,email,optional=phone;verify=1;redirect_uri=http%3A%2F%2F<?= $socUlr?>;receiver=http%3A%2F%2F<?= $_SERVER['HTTP_HOST']?>%2Fxd_custom.html">
			<a href="javascript:void(0);">
				<button class="btn btn-signin-fb" data-uloginbutton="facebook">
					<div class="btn btn-ico btn-ico-vk"></div>
					<?= $this->t('Войти через Facebook');?>
				</button>
			</a>
			<div class="social-auth-more">
				<button class="btn btn-more"></button>
				<ul class="sub-nav">
					<li><a href="javascript:void(0);" data-uloginbutton="linkedin">LinkedIn</a></li>
					<li><a href="javascript:void(0);" data-uloginbutton="googleplus">Google+</a></li>
					<li><a href="javascript:void(0);" data-uloginbutton="twitter">Twitter</a></li>
					<!--<li><a href="javascript:void(0);" data-uloginbutton="vkontakte"><?/*= $this->t('вКонтакте');*/?></a></li>-->
				</ul>
			</div>
		</div>

		<form id="form-register" action="<?= $this->url(array('module'=>'api', 'controller'=>'site', 'action'=>'register'), null, true);?>" method="post" onsubmit="return false">
			<input type="hidden" name="promo-key" value="<?= $this->vPromoKey?>">
			<div class="input-group">

				<input id="email" name="email" type="email" placeholder="<?= $this->t('Электронная почта');?>">
				<span id="error-email" class="error-form-msg" style="display: none;"></span>
				<input id="psw" name="psw" type="password" placeholder="<?= $this->t('Пароль');?>">
				<span id="error-psw" class="error-form-msg" style="display: none;"></span>
				<input id="psw_repeat" name="psw_repeat"type="password" placeholder="<?= $this->t('Повторите пароль');?>">
				<span id="error-psw_repeat" class="error-form-msg" style="display: none;"></span>
				<div class="radio-group" id="sex">
                    <label><input id="sex-female" type="radio" name="sex" value="female"> <?= $this->t('Женщина');?></label>
                    <label><input id="sex-male" type="radio" name="sex" value="male"> <?= $this->t('Мужчина');?></label>
                </div>
				<span id="error-sex" class="error-form-msg" style="display: none;"></span>
				<input id="promocode" name="promocode" type="text" placeholder="<?= $this->t('Промо-код (при наличии)');?>">
				<span id="error-promocode" class="error-form-msg" style="display: none;"></span>
			</div>
			<label><input id="agree" name="agree" type="checkbox" value="yes" checked="checked"> <? printf($this->t('Я принимаю  <a href="%s">правила использования</a>'), $this->url(array('module'=>'about', 'controller'=>'index', 'action'=>'rules'), null, true))?></label>
			<span id="error-agree" class="error-form-msg" style="display: none;"></span>
			<button class="btn btn-dark btn-submit" onclick="return registerClub()"><?= $this->t('Вступить в клуб');?></button>
		</form>
		
	</div>
</div>