<?
$profile = $this->myProfile;
?>
<div class="content" id="wizard">
	<div class="container">
		<div class="content-blocks-container">
			<div class="content-main-col">
				<div class="content-block wizard-main-nav">
					<div class="header">
						<h3><?= $this->t('Ваша анкета находится на рассмотрении у администратора Клуба.');?></h3>
						<p><?= $this->t('Рассмотрение анкеты может занять некоторое время, так как мы её проверяем вручную.');?></p>
						<p><?= $this->t('После рассмотрения Вашей заявки мы вышлем Вам письмо.');?></p>
					</div>
					<div class="data">
						<h1 class="step"><?= $this->t('Преимущества для членов Клуба');?></h1>
						<ol style="margin: 10px 20px;">
							<li><?= $this->t('Знакомства и деловые связи с интересными и образованными людьми Вашего круга.');?></li>
							<li><?= $this->t('Вечеринки в лучших клубах и барах города, светские и деловые мероприятия.');?></li>
							<li><?= $this->t('Специальные предложения и привилегии от многочисленных партнеров Клуба.');?></li>
						</ol>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
