<?php

$this->headScript()->appendFile('/js/event/action.js');

$title = $this->t('Изменить мероприятие');
$this->headTitle($title);


?>

<div class="page-title">
	<h1><?= $title ?></h1>
</div>
<? if (isset($this->vSaveEdit)) : ?>
	<h2 class="text-success"><?= $this->t('Изменения сохранены'); ?></h2>
<? endif; ?>
<table class="table table-bordered">
	<? foreach ($this->vEventsAll as $event): ?>
		<tr id="EventID_<?= $event['id'] ?>" <? if ($event['date_close'] <= CURRENT_DATETIME) echo ' style="background-color: #eee;"' ?>>
			<td><?= $event['date_start'] ?></td>
			<td><?= $event['title'] ?></td>
			<td>
				<form action="<?= $this->url() ?>"><input type="hidden" name="edit" value="go"><input type="hidden" name="event_id" value="<?= $event['id'] ?>">
					<button class="btn btn-info"><?= $this->t('Редактировать'); ?></button>
				</form>
			</td>
			<td>
				<button class="btn btn-danger" onclick="return delEvent(this)" data-eventId="<?= $event['id'] ?>"><?= $this->t('Удалить'); ?></button>
			</td>
		</tr>
	<? endforeach; ?>
</table>
