<?
// js Функционал для мероприятий
$this->inlineScript()->appendFile('/js/event.js');

// js Функционал для обеспечения лайков
$this->inlineScript()->appendFile('/js/like.js');

$title = $this->t('Афиша');
$this->headTitle($title);
?>
<div class="content" id="events">
	<div class="container">
		<?= $this->render('event/nav-bar.phtml');?>

		<div id="events-container"><?
			if(!empty ($this->vEventsNoStart)) {
				foreach($this->vEventsNoStart as $event) {
					$isIGoEvent = (!empty($this->vIgoEvent[$event['id']])) ? true : false; // Иду ли я на это мероприятие?
					$isICheckIn = (!empty($this->vICheckIn[$event['id']])) ? true : false; // Я уже на мероприятии?
					echo $this->partial('event/preview.phtml', array('vEvent'=>$event, 'vMyProfile'=>$this->vMyProfile, 'isIgoEvent'=>$isIGoEvent, 'isICheckIn'=>$isICheckIn));
				}
			} else {
				echo '<h1>'.$this->t('В запрошенной категории мероприятий нет.').'</h1>';
			}
			?>
		</div>
	</div>
</div>