<?
// js Функционал для мероприятий
$this->inlineScript()->appendFile('/js/event.js');

/*
$event = array(15) {
  ["id"] => string(2) "42"
  ["cat_id"] => string(1) "2"
  ["user_id"] => string(4) "3040"
  ["title"] => string(4) "TExt"
  ["anons"] => string(5) "Anons"
  ["full_text"] => string(23) "полный текст"
  ["point_name"] => string(29) "Красная площадь"
  ["date_create"] => string(19) "2014-05-12 10:52:01"
  ["date_start"] => string(19) "2014-05-13 10:00:00"
  ["date_close"] => string(19) "2014-05-13 11:00:00"
  ["otl"] => string(2) "no"
  ["price"] => NULL
  ["money_type"] => NULL
  ["intro_img"] => NULL
  ["del"] => string(2) "no"
}
*/
?>

<div class="content" id="events">
    <? if(Models_User_Model::getMyCurrentStatus() < 70): ?>
	<div class="container">
		<?= $this->render('event/nav-bar.phtml');?>
		<div id="events-container">
			<h2><?= $this->t('Данный функционал доступен только члена Клуба');?></h2>
			<? printf($this->t('Пожалуйста, заполните <a href="%s">Ваш профиль</a> и отправьте администратору.'), $this->url(array('module'=>'user', 'controller'=>'profile', 'action'=>'settings'), null, true))?>
		</div>
	</div>
	<? return; endif;?>

	<div class="container">
		<?= $this->render('event/nav-bar.phtml'); ?>

		<div id="events-container">
			<? if(!empty($this->vEventsMy)) { ?>
			<? foreach ($this->vEventsMy as $event): ?>
				<div class="item-event" id="EventID_<?= $event['id'] ?>">
					<div class="date">
						<span class="month"><?= date_format(new DateTime($event['date_start']), 'M') ?></span>
						<span class="num"><?= date_format(new DateTime($event['date_start']), 'd') ?></span>
					</div>
					<a href="<?= $this->url(array('module' => 'user', 'controller' => 'event', 'action' => 'view', 'id' => $event['id']), null, true) ?>" class="photo">
						<img src="<?= (!is_null($event['intro_img'])) ? $event['intro'] : 'http://www.placehold.it/400x300/eee/aaa&text=no-image'; ?>">
					</a>

					<div class="info">
						<div class="type"><?= $event['cat_name'] ?></div>
						<a href="<?= $this->url(array('module' => 'user', 'controller' => 'event', 'action' => 'view', 'id' => $event['id']), null, true) ?>" class="name"><?= $event['title'] ?></a>

						<div class="controls">
							<form style="margin: 0;" action="<?= $this->url(array('module' => 'user', 'controller' => 'event', 'action' => 'edit'), null, true) ?>"><input type="hidden" name="edit" value="go"><input type="hidden" name="event_id" value="<?= $event['id'] ?>">
								<button class="btn btn-dark btn-med" title="<?= $this->t('Редактировать'); ?>"><?= $this->t('Редактировать'); ?></button>
							</form>
							<button class="btn btn-light btn-med" onclick="return eventDelete(this)" data-eventId="<?= $event['id'] ?>" title="<?= $this->t('Удалить'); ?>"><?= $this->t('Удалить'); ?></button>
						</div>
					</div>
				</div>
			<? endforeach; ?>
			<? } else { ?>
				<h1><?= $this->t('Вы не создавали своих мероприятий.') ?></h1>
			<? } ?>
		</div>
	</div>
</div>
