<?php $this->doctype(Zend_View_Helper_Doctype::XHTML1_STRICT);?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?= $this->translate()->getLocale()?>" lang="<?= $this->translate()->getLocale()?>" dir="ltr">
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />

	<?php
	$this->headMeta()
		->appendName('viewport', 'initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=0,width=device-width')
		->appendName('apple-mobile-web-app-capable', 'yes')
		->appendName('apple-mobile-web-app-status-bar-style', 'black');
	echo $this->headMeta();

	echo $this->headTitle('OnTheList');

	// STYLE
	echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon','href' => '/img/favicon.ico'))
		->appendStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800&subset=latin,cyrillic-ext,cyrillic')
		->appendStylesheet('/css/reset.css')
		->appendStylesheet('/css/main.css')
		->appendStylesheet('/css/base.css');

	// END STYLE

	?>

	<!-- Script -->
	<script type="text/javascript">
		var SERVER_NAME    = '<?= $_SERVER['SERVER_NAME']?>';
		var LANG           = '<?= $this->translate()->getLocale()?>';
		var MY_ID          = <?= Models_User_Model::getMyId()?>;
		var MY_UID         = '<?= Models_User_Model::getMyUid()?>';
		var MY_FIRST_NAME  = '<?= Models_User_Model::getMyFirstName()?>';
		var MY_LAST_NAME   = '<?= Models_User_Model::getMyLastName()?>';
		var MY_AVATAR      = '<?= Models_User_Model::getAvatarUser()?>';
		var MY_PROFILE_URL = '<?= $this->url(array('module'=>'user', 'controller'=>'profile', 'action'=>'index'),null, true)?>';
	</script>
	<script src="http://<?= $_SERVER['SERVER_NAME']?>:8080/socket.io/socket.io.js"></script>

	<?php
	echo $this->headScript()
		->prependFile('/js/main.js')
		->prependFile('/js/libs/jquery.Jcrop.min.js')
		->prependFile('/js/libs/jquery.form.js')
		->prependFile('/js/socket/client.js')
		->prependFile('/js/timeago/locales/jquery.timeago.'.$this->translate()->getLocale().'.js')
		->prependFile('/js/timeago/jquery.timeago.js')
		->prependFile('/js/libs/html5.js', 'text/javascript', array('conditional' => 'lt IE 9'))
		->prependFile('/js/libs/jquery.min.js');
	?>
</head>

<body>
<div class="wrap">
	<div  class="aside-left"><?= $this->render('menu-mobile-left.phtml'); // Основное (полное) меню для мобильных ?></div>
	<div class="contain">
		<div id="header">
			<div class="container">
				<a href="<?= $this->url(array('module'=>'user', 'controller'=>'dashboard', 'action'=>'index'), null, true);?>" class="header-logo hidden-mobile-tablet"></a>
				<?php
				// Верхнее меню для десктопов
				echo $this->render('menu-desktop.phtml');

				// Меню пользователя для десктопов
				echo  $this->render('menu-desktop-user.phtml');

				// Верхнее меню для мобильных
				echo  $this->render('menu-mobile-top.phtml');
				?>
			</div>
			<div id="alerts"><div class="alert"></div></div>
		</div>
		<?= $this->layout()->content;?>
	</div>
</div>
<?= $this->inlineScript();?>
</body>
</html>