<?php

$title = $this->t('О нас пишут');
$this->headTitle($title);

?>

<div class="container" id="news">
	<h1 class="page-title"><?= $title?></h1>
	<? foreach($this->vData as $item) : ?>
		<div class="news-item">
			<a class="photo" href="<?= $item['url']?>" target="_blank"><img src="/img/news/mass-media/<?= $item['id'];?>.jpg"></a>
			<div class="article">
				<h2><a  href="<?= $item['url']?>" target="_blank"><?= $item['title']?></a></h2>
				<div class="date"><?
					$date = new Sas_Date($item['date_create']);
					echo $date->getDateString();
					?></div>
				<span class="hidden-mobile"><?= $item['anons']?></span>
			</div>
		</div>
	<? endforeach; ?>
</div>
