<div id="gallery">
	<div class="info">
		<div id="gallery-paginator" class="paginator"></div>
		<div class="caption" id="gallery-caption"></div>
		<button class="btn btn-ico btn-ico-delete gallery-control-close"></button>
		<div id="gallery-like"></div>
	</div>
	<div class="photo">
		<img src="" id="gallery-image">
	</div>
	<button class="gallery-control Prev"><span class="arr arr-l"></span></button>
	<button class="gallery-control Next "><span class="arr arr-r"></span></button>
</div>
