<div id="popup" class="popup" >
    <div class="cover" onclick="popup_close()"></div>
    <div class="popup-body" id="popup-avatar-edit">
        <div class="title">
            <h2><?= $this->vTitle;?></h2>
            <button onclick="popup_close()" class="btn btn-ico btn-ico-delete btn-close" title="<?= $this->t('Закрыть');?>"></button>
        </div>
        <div class="data">
            <div class="editing-image">
                <img src="<?= $this->vPathImg.'original.jpg?' . time() ?>" id="editing-image">
            </div>
            <form id="cropForm" action="<?= $this->url(array('module'=>'api', 'controller'=>'user', 'action'=>'avatar-crop'), null, true);?>" method="post">
                <input type="hidden" id="x" name="x" />
                <input type="hidden" id="y" name="y" />
                <input type="hidden" id="w" name="w" />
                <input type="hidden" id="h" name="h" />
            </form> 
            <button class="btn btn-light btn-med btn-rotate"><?= $this->t('Повернуть на 90°');?></button>
        </div>
        <div class="controls">
            <button class="btn btn-dark btn-med btn-save"><?= $this->t('Сохранить');?></button>
            <button class="btn btn-light btn-med btn-cancel"><?= $this->t('Отмена');?></button>
        </div>
    </div>
</div>